# config/packages/security.yaml
security:
  role_hierarchy:
    ROLE_STUDENT:     [ROLE_USER]
    ROLE_MODERATOR:   [ROLE_STUDENT]
    ROLE_ADMIN:       [ROLE_MODERATOR]
  access_decision_manager:
    strategy: affirmative
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
      logout:
        path: app_logout
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800
        path: /
      access_denied_handler: App\Security\AccessDeniedHandler

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/recipes/new, roles: ROLE_USER }
    - { path: ^/recipes/\d+/edit, roles: ROLE_USER }
    - { path: ^/recipes/\d+/delete, roles: ROLE_USER }
