version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: cookbook_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cookbook_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cookbook_user
      MYSQL_PASSWORD: cookbook_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: cookbook_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://cookbook_user:cookbook_password@database:3306/cookbook_db"
      APP_ENV: "dev"
      APP_DEBUG: "1"

  nginx:
    image: nginx:alpine
    container_name: cookbook_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql_data:
